version: "3.9"
services:
  mcp-agent:
    build: .
    container_name: mcp-agent
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
    stdin_open: true
    tty: true
    restart: unless-stopped
